# A Brief Introduction to NumPy
### The foundation of scientific computing with Python

In this notebook, we will cover the basics of NumPy, an efficient package that is the basis for many other libraries in the data science ecosystem. Let's get started.

In [1]:
import numpy as np

# Arrays
The array data structure is the backbone of the NumPy library. They can be single-dimensional (vectors), two-dimensional (matrices), or multi-dimensional for more complex projects.

# 1. Building NumPy Arrays
They can be instantiated with the .array() method, using standard python lists or lists of lists

## 1.1 Python Lists

In [3]:
std_list = [1, 2, 3, 4, 5]
np.array(std_list)

array([1, 2, 3, 4, 5])

In [5]:
std_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np.array(std_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Note: the .array() method is a convenience function for constructing objects of the class ndarray. While it is possible to call .ndarray() directly, it is specifically regarded as an anti-pattern by the NumPy documentation.

## 1.2 Built-in Methods

### .arange()
Return evenly spaced values within a given interval.

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.arange(0,20,5)

array([ 0,  5, 10, 15])

### .zeros(), .ones()
Return a new array of given shape and type, filled with zeros or ones.

In [19]:
np.zeros(3)

array([0., 0., 0.])

In [22]:
np.ones(17)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
# Notice the shape represented as a tuple
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### .full()
Return a new array of given shape and type, filled with fill_value.

In [68]:
np.full((4,4), 72)

array([[72, 72, 72, 72],
       [72, 72, 72, 72],
       [72, 72, 72, 72],
       [72, 72, 72, 72]])

### .linspace()
Return evenly spaced numbers over a specified interval.

In [24]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [27]:
np.linspace(0,1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

Note: the main difference between .linspace() and .arange() is that with .linspace() you have precise control over the end value, whereas with .arange() you can specify the increments directly.

## 1.3 Random

### .rand()
Create an array of the given shape and populate it with random samples from a uniform distribution over [0,1)

In [47]:
np.random.rand()

0.3804526800129031

In [52]:
np.random.rand(4)

array([0.72030054, 0.7577563 , 0.19300993, 0.66114322])

In [53]:
np.random.rand(7,3)

array([[0.28267269, 0.13092963, 0.05444909],
       [0.93517076, 0.58986222, 0.12696837],
       [0.21713472, 0.42376648, 0.37529574],
       [0.62436726, 0.0208025 , 0.20361059],
       [0.89958279, 0.65010572, 0.32282345],
       [0.00584939, 0.28439417, 0.50719887],
       [0.61906857, 0.17249316, 0.95261216]])

### .randn()
Return a sample (or samples) from the “standard normal” distribution.

In [39]:
np.random.randn()

0.36910179629879897

In [46]:
np.random.randn(5)

array([-0.08320502, -0.69825957,  0.80139519,  0.53540454,  0.78953503])

Note: .rand() is from a uniform distribution, whereas .randn() is from the standard **normal** distribution.

In [55]:
np.random.randn(3, 5)

array([[ 1.33667905,  0.46529544,  1.51069451,  0.69167808,  1.60270943],
       [ 1.62614154, -0.10463841, -0.999014  , -0.70942201, -0.15136812],
       [-0.70328834, -0.48982338,  2.03118893,  2.32867839,  2.08885297]])

### .randint()
Return random integers from low (inclusive) to high (exclusive).

In [60]:
np.random.randint(0,10)

9

In [66]:
np.random.randint(0,10,size=7)

array([4, 5, 5, 6, 1, 2, 1])

In [67]:
np.random.randint(0,10,size=(3,2))

array([[9, 3],
       [6, 8],
       [7, 6]])

## 2.1 Attributes and Methods

In [ ]:
arr = np.random.randint(0,10,size=(2,7))
arr

### .shape
Tuple of array dimensions. Note: this is an attribute NOT a method.

In [76]:
arr.shape

(2, 7)

### .reshape()
Gives a new shape to an array without changing its data. Note: this happens 'in place' (does not return new values).

In [78]:
arr.reshape(7,2)

array([[9, 5],
       [7, 3],
       [6, 8],
       [9, 9],
       [6, 1],
       [1, 4],
       [2, 3]])

In [79]:
arr.reshape(12,4)

ValueError: cannot reshape array of size 14 into shape (12,4)

### .dtype
The type of data in the array.

In [80]:
arr.dtype

dtype('int64')

### .astype()
Casts values to a specified type.

In [83]:
arr.astype('int8')

array([[9, 5, 7, 3, 6, 8, 9],
       [9, 6, 1, 1, 4, 2, 3]], dtype=int8)

In [81]:
arr.astype('complex')

array([[9.+0.j, 5.+0.j, 7.+0.j, 3.+0.j, 6.+0.j, 8.+0.j, 9.+0.j],
       [9.+0.j, 6.+0.j, 1.+0.j, 1.+0.j, 4.+0.j, 2.+0.j, 3.+0.j]])

In [114]:
arr2 = np.full((4,4), 199)

In [115]:
arr2.astype('bool')

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])